version: '3.3'

services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - static:/label-studio/label_studio/core/static_build/:rw
      - media:/label-studio/label_studio/core/media/:rw
      - lsf:/label-studio/frontend/dist/lsf/:rw
      - react:/label-studio/frontend/dist/react-app:rw
      - ./nginx/:/etc/nginx/conf.d/:ro
      - avatars:/label-studio/label_studio/core/media/avatars:rw
    depends_on:
      - app
    command: nginx -g "daemon off;"

  app:
    build: ./
    expose:
      - "8080"
    depends_on:
      - db
    command: [ "uwsgi", "--ini",  "./uwsgi.ini", "--chdir", "./label_studio" ]
    
  db:
    image: postgres:11.5
    hostname: db
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ${POSTGRES_DATA_DIR:-./postgres-data}:/var/lib/postgresql/data
    ports:
      - 5432:5432


volumes:
  static: {}
  media: {}
  lsf: {}
  react: {}
  frontend: {}
  avatars: {}
